-- Tabla de Colonias Zihuatanejo
CREATE TABLE IF NOT EXISTS public.colonias (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  habitantes integer NOT NULL,
  viviendas integer NOT NULL,
  personas_por_lote numeric NOT NULL,
  lat numeric NOT NULL,
  lng numeric NOT NULL
);

-- Habilitar RLS (opcional)
ALTER TABLE public.colonias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Las colonias son publicas" ON public.colonias FOR SELECT USING (true);

-- Insertando datos
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('12 de Marzo', 1250, 335, 3.7, 17.65054, -101.55921) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('12 de Marzo Parte Alta', 860, 232, 3.7, 17.64515, -101.56405) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('16 de Mayo', 1480, 400, 3.7, 17.6402, -101.54982) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('16 de Septiembre', 2150, 580, 3.7, 17.63444, -101.54764) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('20 de Noviembre', 1720, 465, 3.7, 17.63661, -101.56133) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('24 de Abril', 1050, 285, 3.7, 17.63257, -101.55401) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('6 de Enero', 780, 210, 3.7, 17.64843, -101.54687) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Aeropuerto', 1340, 362, 3.7, 17.64015, -101.55167) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Agua de Correa', 5850, 1580, 3.7, 17.6458, -101.55049) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Amuzgos', 920, 248, 3.7, 17.6342, -101.5498) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Aquiles Serdán', 1640, 443, 3.7, 17.64911, -101.55137) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Barrio Nuevo', 2760, 746, 3.7, 17.6375, -101.55826) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Barrio Viejo', 3950, 1068, 3.7, 17.63849, -101.55504) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Benito Juárez', 2440, 659, 3.7, 17.64157, -101.55158) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Buenavista', 1180, 319, 3.7, 17.6446, -101.56147) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Club de Golf', 740, 190, 3.9, 17.64383, -101.55539) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Coacoyul', 8950, 2419, 3.7, 17.63717, -101.5609) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Convergencia', 690, 186, 3.7, 17.65014, -101.55716) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('CTM', 1210, 327, 3.7, 17.6404, -101.56016) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Cuauhtémoc', 1760, 476, 3.7, 17.64744, -101.54916) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Darío Galeana', 1040, 281, 3.7, 17.63885, -101.55593) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Almacén', 580, 157, 3.7, 17.63745, -101.5503) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Barril', 960, 259, 3.7, 17.63621, -101.54994) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Barril I', 640, 173, 3.7, 17.64682, -101.56413) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Barril II', 710, 192, 3.7, 17.64402, -101.56351) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Barril III', 760, 205, 3.7, 17.64779, -101.5652) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Calabazal', 2380, 643, 3.7, 17.64733, -101.55967) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Calabazalito', 590, 159, 3.7, 17.64455, -101.54693) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Calechoso', 420, 114, 3.7, 17.64988, -101.55544) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Embalse', 6750, 1824, 3.7, 17.64035, -101.56524) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Hujal', 4420, 1195, 3.7, 17.63739, -101.54554) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Limón', 760, 205, 3.7, 17.64567, -101.55833) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Mirador', 1110, 300, 3.7, 17.63778, -101.55227) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Paraíso', 680, 184, 3.7, 17.63467, -101.5556) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Posquelite', 410, 111, 3.7, 17.64956, -101.56437) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('El Zarco', 540, 146, 3.7, 17.64976, -101.55443) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Emiliano Zapata', 5420, 1465, 3.7, 17.64983, -101.55564) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('FOVISSSTE', 1880, 510, 3.7, 17.64749, -101.5583) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Golondrinas', 1320, 357, 3.7, 17.63872, -101.55692) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Infonavit El Hujal', 2940, 795, 3.7, 17.63239, -101.54579) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Infonavit La Boquita', 1720, 465, 3.7, 17.6416, -101.5557) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Infonavit La Noria', 1280, 346, 3.7, 17.64441, -101.55451) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Infonavit La Parota', 1040, 281, 3.7, 17.63801, -101.56449) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Ixtapa', 6950, 1780, 3.9, 17.64298, -101.55638) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Ixtapa las Palmas', 1260, 340, 3.7, 17.63303, -101.56051) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Ixtapa Zihuatanejo', 8850, 2270, 3.9, 17.63868, -101.5626) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('José María Morelos', 2140, 578, 3.7, 17.64774, -101.56255) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Esperanza', 980, 265, 3.7, 17.63821, -101.55208) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Joya', 1260, 340, 3.7, 17.63702, -101.56065) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Laja', 2350, 635, 3.7, 17.64908, -101.54684) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Madera', 1180, 300, 3.9, 17.63526, -101.5577) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Moraleja', 720, 195, 3.7, 17.64333, -101.5471) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Presa', 890, 241, 3.7, 17.63258, -101.56328) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Puerta', 2420, 654, 3.7, 17.64636, -101.55583) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Ropa', 960, 245, 3.9, 17.65091, -101.55197) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('La Salitrera', 1180, 319, 3.7, 17.6346, -101.55349) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Las Huertas', 1060, 286, 3.7, 17.63349, -101.55918) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Las Mesas', 520, 141, 3.7, 17.64907, -101.5574) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Las Ollas', 430, 116, 3.7, 17.63325, -101.56521) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Las Pozas', 640, 173, 3.7, 17.64977, -101.55102) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Lázaro Cárdenas', 2860, 773, 3.7, 17.63877, -101.56362) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Loma Bonita', 1820, 492, 3.7, 17.64373, -101.54748) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Lomas del Riscal', 1120, 303, 3.7, 17.63237, -101.55093) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Los Achotes', 2050, 554, 3.7, 17.64875, -101.56415) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Los Almendros', 860, 232, 3.7, 17.64933, -101.56128) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Los Electricistas', 620, 168, 3.7, 17.63729, -101.55901) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Marina Ixtapa', 1050, 270, 3.9, 17.63661, -101.55696) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Miramar', 1260, 340, 3.7, 17.63511, -101.56298) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Nuevo Amanecer', 840, 227, 3.7, 17.64852, -101.56471) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Pantla Centro', 2260, 611, 3.7, 17.6457, -101.5512) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Pelícanos', 1180, 319, 3.7, 17.64536, -101.54669) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Pelícanos II', 760, 205, 3.7, 17.64273, -101.54867) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Plan de Hernández', 520, 141, 3.7, 17.63176, -101.54783) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Primer Paso Cardenista', 1320, 357, 3.7, 17.65028, -101.55346) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Progreso', 3620, 978, 3.7, 17.64688, -101.55023) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Progreso Parte Alta', 1420, 384, 3.7, 17.6371, -101.55086) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Rabo de Iguana', 390, 105, 3.7, 17.6476, -101.54872) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Real de Guadalupe', 1080, 292, 3.7, 17.63727, -101.5532) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('San Ignacio', 820, 222, 3.7, 17.63568, -101.54757) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('San Miguelito', 1240, 335, 3.7, 17.63444, -101.5544) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Vallecitos de Zaragoza', 2480, 670, 3.7, 17.63786, -101.56187) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Vaso de Miraflores', 540, 146, 3.7, 17.64585, -101.56213) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Vicente Guerrero', 2740, 741, 3.7, 17.63869, -101.55256) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Villas del Pacifico', 1020, 261, 3.9, 17.63164, -101.56088) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Villas del Valle', 940, 240, 3.9, 17.63834, -101.55885) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Villas las Garzas', 780, 200, 3.9, 17.63112, -101.55268) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Zihuatanejo Centro', 7850, 2010, 3.9, 17.64785, -101.55214) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Zona Hotelera I', 620, 170, 3.6, 17.64811, -101.56137) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Zona Hotelera II', 510, 142, 3.6, 17.63482, -101.56224) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;
INSERT INTO public.colonias (nombre, habitantes, viviendas, personas_por_lote, lat, lng) VALUES ('Zona Industrial', 1340, 362, 3.7, 17.63134, -101.55905) ON CONFLICT (nombre) DO UPDATE SET lat = EXCLUDED.lat, lng = EXCLUDED.lng, habitantes = EXCLUDED.habitantes, viviendas = EXCLUDED.viviendas, personas_por_lote = EXCLUDED.personas_por_lote;