const fs = require('fs');
const path = require('path');

const coloniasSqlPath = path.join(__dirname, '01_crear_colonias.sql');
let coloniasSql = fs.readFileSync(coloniasSqlPath, 'utf8');

const setupLines = [];

setupLines.push(`-- =========================================================================`);
setupLines.push(`-- 1. TABLA STREETS (Reportes Ciudadanos)`);
setupLines.push(`-- =========================================================================`);
setupLines.push(`CREATE TABLE IF NOT EXISTS public.streets (`);
setupLines.push(`  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,`);
setupLines.push(`  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,`);
setupLines.push(`  street_name text NOT NULL,`);
setupLines.push(`  colonia text NOT NULL,`);
setupLines.push(`  lat numeric NOT NULL,`);
setupLines.push(`  lng numeric NOT NULL,`);
setupLines.push(`  length_m numeric NOT NULL,`);
setupLines.push(`  via_type text NOT NULL,`);
setupLines.push(`  traffic_type text NOT NULL,`);
setupLines.push(`  num_viviendas integer NOT NULL,`);
setupLines.push(`  near_school boolean DEFAULT false,`);
setupLines.push(`  near_hospital boolean DEFAULT false,`);
setupLines.push(`  near_market boolean DEFAULT false,`);
setupLines.push(`  near_transport boolean DEFAULT false,`);
setupLines.push(`  rain_risk integer NOT NULL,`);
setupLines.push(`  description text,`);
setupLines.push(`  photo_urls text[] DEFAULT '{}'::text[],`);
setupLines.push(`  impact_score integer NOT NULL,`);
setupLines.push(`  priority text NOT NULL,`);
setupLines.push(`  status text DEFAULT 'PENDIENTE'::text,`);
setupLines.push(`  admin_notes text,`);
setupLines.push(`  reporter_name text NOT NULL,`);
setupLines.push(`  reporter_phone text`);
setupLines.push(`);`);
setupLines.push(``);
setupLines.push(`-- Habilitar RLS para streets`);
setupLines.push(`ALTER TABLE public.streets ENABLE ROW LEVEL SECURITY;`);
setupLines.push(``);
setupLines.push(`-- Politicas: todos pueden insertar (reportes anonimos), solo admins pueden ver/modificar`);
setupLines.push(`CREATE POLICY "Permitir insercion anonima" ON public.streets FOR INSERT WITH CHECK (true);`);
setupLines.push(`CREATE POLICY "Lectura publica temporal" ON public.streets FOR SELECT USING (true);`);
setupLines.push(`CREATE POLICY "Update publico temporal" ON public.streets FOR UPDATE USING (true);`);
setupLines.push(`CREATE POLICY "Delete publico temporal" ON public.streets FOR DELETE USING (true);`);
setupLines.push(``);
setupLines.push(`-- =========================================================================`);
setupLines.push(`-- 2. TABLA COLONIAS Y DATOS`);
setupLines.push(`-- =========================================================================`);
setupLines.push(coloniasSql);
setupLines.push(``);
setupLines.push(`-- =========================================================================`);
setupLines.push(`-- 3. STORAGE BUCKET (Fotos)`);
setupLines.push(`-- =========================================================================`);
setupLines.push(`INSERT INTO storage.buckets (id, name, public) VALUES ('street_photos', 'street_photos', true) ON CONFLICT (id) DO NOTHING;`);
setupLines.push(``);
setupLines.push(`-- Politicas para el bucket`);
setupLines.push(`CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'street_photos');`);
setupLines.push(`CREATE POLICY "Anon Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'street_photos');`);
setupLines.push(``);

const finalSqlPath = path.join(__dirname, '00_setup_completo.sql');
fs.writeFileSync(finalSqlPath, setupLines.join('\n'));
console.log(`Archivo generado con éxito: ${finalSqlPath}`);
